### ISSUE TITLE
Won't build on Debian 9.3

### ISSUE THREAD

**Issue by seefood** [sideeffect42/SpectreTester#1]
# make
mkdir -p 'bin'
cc -pipe -Wall -g -O0 -o 'bin/spectreO0' spectre.c
In file included from /usr/lib/gcc/i686-linux-gnu/6/include/xmmintrin.h:1249:0,
                 from /usr/lib/gcc/i686-linux-gnu/6/include/x86intrin.h:33,
                 from spectre_intrinsics.h:50,
                 from spectre.c:7:
spectre.c: In function ‘read_memory_byte’:
/usr/lib/gcc/i686-linux-gnu/6/include/emmintrin.h:1479:1: error: inlining failed in call to always_inline ‘_mm_clflush’: target specific option mismatch
 _mm_clflush (void const *__A)
 ^~~~~~~~~~~
spectre.c:56:4: note: called from here
    _mm_clflush(&array2[i * 512]); /* intrinsic for clflush instruction */
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/lib/gcc/i686-linux-gnu/6/include/xmmintrin.h:1249:0,
                 from /usr/lib/gcc/i686-linux-gnu/6/include/x86intrin.h:33,
                 from spectre_intrinsics.h:50,
                 from spectre.c:7:
/usr/lib/gcc/i686-linux-gnu/6/include/emmintrin.h:1479:1: error: inlining failed in call to always_inline ‘_mm_clflush’: target specific option mismatch
 _mm_clflush (void const *__A)
 ^~~~~~~~~~~
spectre.c:70:4: note: called from here
    _mm_clflush(&array1_size);
    ^~~~~~~~~~~~~~~~~~~~~~~~~
Makefile:33: recipe for target 'bin/spectreO0' failed
make: *** [bin/spectreO0] Error 1

**Comment by sideeffect42** [comment]
The true issue here is that GCC doesn't know the `clflush` instruction, which  needs a CPU that supports SSE2.
Can you elaborate a bit more on the CPU model you have?

If your CPU supports SSE2 you could try adding `-msse2` or `-march=native` to your CFLAGS.
